WEBComputadora.View/Controllers/ComputadoraMemoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEBComputadora.DAL.Contexts;
using WEBComputadora.View.Services;
using WEBComputadora.View.Services.Interfaces;

namespace WEBComputadora.Controllers
{
    [RoutePrefix("computadoras")]
    public class ComputadoraMemoriaController : Controller
    {
        private readonly IComputadoraMemoriaServicio servicio = new ComputadoraMemoriaServicio();

        private const string partialViewsPath = "~/Views/ComputadoraMemoria";

        [Route("ver"), HttpGet]
        public async Task<ActionResult> Display(int? computadoraId, int? computadoraMemoriaId)
        {
            var modelo = await servicio.GetComputerByIdAsync(computadoraId, computadoraMemoriaId)
                                    .ConfigureAwait(false);

            if (modelo != null)
            {
                return View(modelo);
            }
            return RedirectToAction("NotFound", "ErrorHandler");
        }
        [Route(""), HttpGet]
        public ActionResult Index()
        {
            var model = servicio.GetIndex();
            return View(model);
        }
        [Route("IndexGridAsync"), HttpPost]
        public async Task<ActionResult> IndexGridAsync(string descripcion, int? capacidadIgual, int? capacidadMayorGB, 
                                            int? pageSize, bool? changePage, int? toPage)
        {
            var modelo = await servicio.GetComputersAsync(descripcion, capacidadIgual, capacidadMayorGB, 
                                                            pageSize, changePage, toPage).ConfigureAwait(false);

            return PartialView(partialViewsPath + "/IndexGridAsync.cshtml", modelo);
        }
        
    }
}

WEBComputadora.View/Controllers/ErrorHandlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBComputadora.View.Controllers
{
    [RoutePrefix("error")]
    public class ErrorHandlerController : Controller
    {
        [Route("notfound")]
        public ActionResult NotFound()
        {
            return View();
        }
    }
}

WEBComputadora.View/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBComputadora.DAL.Contexts;
using WEBComputadora.View.Services;
using WEBComputadora.View.Services.Interfaces;
using WEBComputadora.View.Utils;

namespace WEBComputadora.Controllers
{
    [RoutePrefix("")]
    public class HomeController : Controller
    {
        private readonly IHomeService service = new HomeService();

        [Route(""), HttpGet]
        public ActionResult Index()
        {
            return View(service.GetIndexModel());
        }

        [Route("update/seed"), HttpGet]
        public ActionResult UpdateSeed()
        {
            service.UpdateSeedFromContext();
            return RedirectToAction("Index");
        }
        [Route("update/wait-time-request"), HttpPost]
        public ActionResult UpdateWaitTimeRequest(int? waitTimeRequest, int? totalRecordsCreate)
        {
            bool isOk = false;

            if (service.SetConfiguration(waitTimeRequest, totalRecordsCreate))
                isOk = true;

            return Json(new { Ok = isOk, WebDbContext.WaitTimeRequest, WebDbContext.TotalRecordsSeed });
        }
    }
}

WEBComputadora.View/Controllers/RESTComputadoraMemoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WEBComputadora.Model.ComputadorasMemorias;
using WEBComputadora.Services;
using WEBComputadora.Services.Interfaces;

namespace WEBComputadora.Controllers
{
    [RoutePrefix("api/obtener")]
    public class RESTComputadoraMemoriaController : ApiController
    {
        private readonly IRESTComputadoraMemoriaServicio servicio = new RESTComputadoraMemoriaServicio();

        [Route("computadoras"), HttpGet]
        public IList<ComputadoraMemoria> GetComputers(string descripcion = "", int capacidadIgual = 0, int capacidadMayorGb = 0)
        {
            return servicio.GetComputers(descripcion, capacidadIgual, capacidadMayorGb);
        }

        [Route("computadora"), HttpGet]
        public ComputadoraMemoria GetComputerById(int computadoraId = 0, int computadoraMemoriaId = 0)
        {
            return servicio.GetComputerById(computadoraId, computadoraMemoriaId);
        }
    }
}

WEBComputadora.View/Views/ComputadoraMemoria/CargarGrilla.cshtml
@model WEBComputadora.Model.ViewModels.ComputadorasMemorias.ComputadoraMemoriaGrillaVistaModelo
@using WEBComputadora.View.Helpers.Html

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Computadoras
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <td></td>
                        <td>Computadora</td>
                        <td>Memoria</td>
                        <td>Capacidad (MB)</td>
                        <td>(GB)</td>
                        <td>Tipo</td>
                        <td>Frecuencia</td>
                    </tr>
                </thead>

                <tbody>
                    @if (Model.Datas != null && Model.Datas.Count > 0)
                    {
                        foreach (var modelItem in Model.Datas)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("Display", "ComputadoraMemoria",
                                                    new
                                                    {
                                                        computadoraId = modelItem.ComputadoraId,
                                                        computadoraMemoriaId = modelItem.ComputadoraMemoriaId
                                                    })" class="btn btn-default btn-sm"
                                       title="Ver @modelItem.Computadora.Descripcion">
                                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    </a>
                                </td>
                                <td>@modelItem.Computadora.Descripcion</td>
                                <td>@modelItem.Memoria.Descripcion</td>
                                <td>@modelItem.Memoria.Capacidad</td>
                                <td>@modelItem.Memoria.CapacidadGigaBytes</td>
                                <td>@modelItem.Memoria.Tipo</td>
                                <td>@modelItem.Memoria.Frecuencia MHz</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="8">
                                No existen datos que mostrar
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            @if (Model.Paginator != null && Model.Paginator.HasPagination)
                            {
                                @Html.PaginatorBar(Model.Paginator.CurrentPage, Model.Paginator.FirstPage, Model.Paginator.LastPage)
                            }
                        </td>
                        <td colspan="2" class="text-right">
                            <div>
                                Total: @Model.TotalRecords
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

WEBComputadora.View/Views/ComputadoraMemoria/Display.cshtml
@model WEBComputadora.Model.ViewModels.ComputadorasMemorias.ComputadoraMemoriaDisplayViewModel

@{
    ViewBag.Title = "Ver " + Model.ComputadoraDescripcion;
}

<h1>@Model.MemoriaDescripcion</h1>
<h2>@Model.ComputadoraDescripcion</h2>

<div class="row">
    <div class="col-xs-12">

    </div>
</div>

WEBComputadora.View/Views/ComputadoraMemoria/Index.cshtml
@model WEBComputadora.Model.ViewModels.ComputadorasMemorias.ComputadoraMemoriaVistaModelo
@using WEBComputadora.View.Helpers.Html


@{
    ViewBag.Title = Model.FormTitle;
}

<div class="row">
    <div class="col-xs-12">
        <h1>@Model.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="top-control">
            <div class="row">
                <div class="col-xs-12">
                    <div id="estado_tabla"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="filters">
                        <div class="row">
                            <div class="col-xs-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.DescripcionFilter, "Memoria")
                                    @Html.TextBoxFor(m => m.DescripcionFilter, new { @class = "form-control", @placeholder = "Descripción memoria" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CapacidadIgualFilter, "Capacidad igual a")
                                    @Html.TextBoxFor(m => m.CapacidadIgualFilter, new { @type = "number", @class = "form-control", @placeholder = "Capacidad mayor a" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CapacidadMayorAFilter, "Capacidad (GB) mayor a")
                                    @Html.TextBoxFor(m => m.CapacidadMayorAFilter, new { @type = "number", @class = "form-control", @placeholder = "Capacidad mayor a" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="button-group-filter">
                                    <div class="pull-right">
                                        <div class="btn-group" role="group">
                                            @Html.DropdownRows("<span class='glyphicon glyphicon-th-list'></span>", Model.PageSize.Size, Model.PageSize.SizeCollection, true)
                                            <button id="BtnActionFilter" class="btn btn-default">
                                                <span class="glyphicon glyphicon-filter"></span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div id="load_tabla"></div>
    </div>
</div>


@section scripts
{
    <script>

    $(document).ready(function () {
        LoadInternalGrid(GetFilterValues());

        $("#BtnActionFilter").click(function () {
            LoadInternalGrid(GetFilterValues());
        });

        $("#buttonChangeRows > ul > li > a").click(function () {
            if ($(this).attr('data-changerows-selected') === undefined)
            {
                var myButtonRowSelected = $(this);

                $('#buttonChangeRows > ul').find('li > a[data-changerows-selected]')
                    .removeAttr('data-changerows-selected')
                    .parent()
                    .removeClass("disabled");

                $(myButtonRowSelected)
                    .attr('data-changerows-selected', '')
                    .parent()
                    .addClass("disabled");


                LoadInternalGrid(GetFilterValues());
            }
        });

        $(document).on("click", "#paginatorBar > ul > li > a", function () {
            if (!$(this).parent().hasClass('active'))
            {
                var data = GetFilterValues();
                data.changePage = true;
                data.toPage = $(this).attr('data-to-page');

                LoadInternalGrid(data);
            }
        })
    });

    function LoadInternalGrid(data)
    {
        url = '@Url.Action("IndexGridAsync", "ComputadoraMemoria")';
        $.ajax({
            data: data,
            url: url,
            type: 'POST',
            beforeSend: function () {
                SetFilterValues(true);
                ShowMessageStatus('Obteniendo datos ...', "info");
                SetLoadTableHTML("");
            },
            success: function (response) {
                ShowMessageStatus('¡Cargado!', "success");
                SetLoadTableHTML(response);
            },
            error: function (response) {
                ShowMessageStatus('¡Ocurrio un error mientras se obtenian los datos!', "danger");
            },
            complete: function () {
                SetFilterValues(false);
            }
        });
    }

    function SetLoadTableHTML(html)
    {
        $("#load_tabla").html(html);
    }

    function SetFilterValues(isReadOnly)
    {
        if (isReadOnly) {
            $('#@Html.IdFor(m => m.DescripcionFilter)').attr('disabled', '');
            $('#@Html.IdFor(m => m.CapacidadIgualFilter)').attr('disabled', '');
            $('#@Html.IdFor(m => m.CapacidadMayorAFilter)').attr('disabled', '');
            $('#buttonChangeRows > button').attr('disabled', '');
            $('#BtnActionFilter').attr('disabled', '');
        }
        else
        {
            $('#@Html.IdFor(m => m.DescripcionFilter)').removeAttr('disabled');
            $('#@Html.IdFor(m => m.CapacidadIgualFilter)').removeAttr('disabled');
            $('#@Html.IdFor(m => m.CapacidadMayorAFilter)').removeAttr('disabled');
            $('#buttonChangeRows > button').removeAttr('disabled');
            $('#BtnActionFilter').removeAttr('disabled');
        }
    }

    function GetFilterValues()
    {
        var filtersObject = new Object();

        filtersObject.descripcion      = $("#@Html.IdFor(m => m.DescripcionFilter)").val();
        filtersObject.capacidadIgual   = $("#@Html.IdFor(m => m.CapacidadIgualFilter)").val();
        filtersObject.capacidadMayorGb = $("#@Html.IdFor(m => m.CapacidadMayorAFilter)").val();
        filtersObject.pageSize         = $("a[data-changerows-selected]").attr("data-changerows-val");

        return filtersObject;
    }

    function ShowMessageStatus(message, type)
    {
        $('#estado_tabla').html("<span class='label label-" + type + "'>" + message + "</span>");
    }

    </script>
}

WEBComputadora.View/Views/ComputadoraMemoria/IndexGridAsync.cshtml
@model WEBComputadora.Model.ViewModels.ComputadorasMemorias.ComputadoraMemoriaGrillaVistaModelo
@using WEBComputadora.View.Helpers.Html

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Computadoras
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <td></td>
                        <td>Computadora</td>
                        <td>Memoria</td>
                        <td>Capacidad (MB)</td>
                        <td>(GB)</td>
                        <td>Tipo</td>
                        <td>Frecuencia</td>
                    </tr>
                </thead>

                <tbody>
                    @if (Model.Datas != null && Model.Datas.Count > 0)
                    {
                        foreach (var modelItem in Model.Datas)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("Display", "ComputadoraMemoria",
                                                    new
                                                    {
                                                        computadoraId = modelItem.ComputadoraId,
                                                        computadoraMemoriaId = modelItem.ComputadoraMemoriaId
                                                    })" class="btn btn-default btn-sm"
                                       title="Ver @modelItem.Computadora.Descripcion">
                                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    </a>
                                </td>
                                <td>@modelItem.Computadora.Descripcion</td>
                                <td>@modelItem.Memoria.Descripcion</td>
                                <td>@modelItem.Memoria.Capacidad</td>
                                <td>@modelItem.Memoria.CapacidadGigaBytes</td>
                                <td>@modelItem.Memoria.Tipo</td>
                                <td>@modelItem.Memoria.Frecuencia MHz</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="8">
                                No existen datos que mostrar
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            @if (Model.Paginator != null && Model.Paginator.HasPagination)
                            {
                                @Html.PaginatorBar(Model.Paginator.CurrentPage, Model.Paginator.FirstPage, Model.Paginator.LastPage)
                            }
                        </td>
                        <td colspan="2" class="text-right">
                            <div>
                                Total: @Model.TotalRecords
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

WEBComputadora.View/Views/ErrorHandler/NotFound.cshtml
@{
    ViewBag.Title = "Error | Not Found";
}

<div class="error-container">
    <div class="header">
        <h1>404 <small>error</small></h1>
    </div>
    <div class="body">
        <p class="lead"><span class="glyphicon glyphicon-remove-sign" style="margin-right: 8px;"></span>Página no encontrada</p>
        <p>
            La página que intentas acceder no fue encontrada o dejo de existir. <br />
            Puedes volver al inicio o usar el navegador superior para acceder a otro lugar.
        </p>
    </div>
</div>

WEBComputadora.View/Views/Home/Index.cshtml
@model WEBComputadora.Model.ViewModels.Home.HomeIndexViewModel
@using WEBComputadora.View.Helpers.Html

<dic class="row">
    <div class="col-xs-12">
        @if (Model.HasMessages)
        {
            <div class="row">
                <div class="col-xs-12">
                    @foreach (var message in Model.Messages)
                    {
                        @Html.AlertMessage(message.Description, message.Type)
                    }
                </div>
            </div>
        }

        @{ Html.RenderPartial("~/Views/Home/Partials/Index_TableRecords.cshtml", Model); }

        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <div class="panel panel-default card">
                    <div class="panel-body">
                        <div class="card-body">
                            <div class="title">
                                <span class="glyphicon glyphicon-cog" style="margin-right: 9px"></span>
                                Configuraciones
                            </div>
                            <hr />

                            <div class="form-group">
                                @Html.LabelFor(m => m.WaitTimeRequest, "Tiempo de espera base datos (ms)")
                                @Html.TextBoxFor(m => m.WaitTimeRequest, new { type = "number", @class = "form-control" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(m => m.TotalRecordsSeed, "Registros a crear")
                                @Html.TextBoxFor(m => m.TotalRecordsSeed, new { type = "number", @class = "form-control" })
                            </div>
                            <hr />
                            <button id="btnUpdateConfiguration" type="button" class="btn btn-primary">Confirmar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</dic>

@section scripts{
    <script>
        $(document).ready(function () {
            $(document).on('click', '#btnUpdateConfiguration', function () {
                var data = new Object();
                data.waitTimeRequest = $('#@Html.IdFor(m => m.WaitTimeRequest)').val();
                data.totalRecordsCreate = $('#@Html.IdFor(m => m.TotalRecordsSeed)').val();

                $.ajax({
                    data: data,
                    url: '@Url.Action("UpdateWaitTimeRequest", "Home")',
                    method: 'POST',
                    beforeSend: function () {
                        $('#btnUpdateConfiguration').attr('disabled', '');
                    },
                    success: function (response) {
                        if (response.Ok) {
                            alert("Se cambio correctamente el tiempo de respuesta del servidor.");
                        }
                        else {
                            alert("No fue posible cambiar el tiempo de respuesta del servidor, asegurese que ingreso un rango entre 0 y 10000.");
                        }
                        $('#@Html.IdFor(m => m.WaitTimeRequest)').val(response.WaitTimeRequest);
                        $('#@Html.IdFor(m => m.TotalRecordsSeed)').val(response.TotalRecordsSeed);
                    },
                    error: function (response) {
                        console.log(reponse);
                    },
                    complete: function () {
                        $('#btnUpdateConfiguration').removeAttr('disabled');
                    }
                });
            });
        });

    </script>
    
    }

WEBComputadora.View/Views/Home/Partials/Index_TableRecords.cshtml
@model WEBComputadora.Model.ViewModels.Home.HomeIndexViewModel

@{
    Layout = string.Empty;
}

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="panel panel-default card">
            <div class="panel-body">
                <div class="card-body">
                    <div class="title">
                        <span class="glyphicon glyphicon-list-alt" style="margin-right: 9px"></span>
                        Registros de base de datos
                    </div>
                    <hr />
                    <ul class="list-simple">
                        @if (Model.HomeDatabasesList.Count > 0)
                        {
                            foreach (var tableItem in Model.HomeDatabasesList.OrderBy(m => m.Order))
                            {
                                <li>
                                    <div class="flex-container-row">
                                        @if (tableItem.IsSubLevel)
                                        {
                                            <div class="fo-1 w-75" style="padding-left:20px">
                                                @tableItem.TableName
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="fo-1 w-75">
                                                @tableItem.TableName
                                            </div>
                                        }

                                        <div class="fo-2 bold font-mono">
                                            @tableItem.TableTotalRecords registros
                                        </div>
                                    </div>
                                </li>
                            }
                            <li>
                                <div class="flex-container-row" style="margin-top: 10px;">
                                    <div class="fo-1 w-75">Total</div>
                                    <div class="fo-2 bold font-mono">
                                        @Model.TotalDatabaseRecords registros
                                    </div>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li> No existen registros para mostrar. </li>
                        }
                    </ul>
                    <hr />
                    <ul class="list-simple">
                        <li>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Semilla: <span class="bold">@Model.SeedNumber</span>
                            @Html.ActionLink("¿Usar otra semilla?", "UpdateSeed", "Home")
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <div class="card">
            <div class="panel-body">
                <div class="card-body">
                    <div class="title">
                        <span style="font-size: 15px;">Menu</span>
                    </div>
                    <hr />
                    <ol class="pl-1">
                        @if (Model.HomeMenusList.Count > 0)
                        {
                            foreach (var menuItem in Model.HomeMenusList)
                            {
                                <li>
                                    @Html.ActionLink(menuItem.Description, menuItem.ActionName, menuItem.RouteName)
                                </li>
                            }
                        }
                        else
                        {
                            <li> No existen registros para mostrar. </li>
                        }
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

WEBComputadora.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>